---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-as-standalone
       state: stopped
    - name: telegram
      telegram:
        token: 'bot765291265:AAFC-buv3Pd_Mu2fwReeLlMhfaiRop5WN_4'
        chat_id: -258533565
        msg: HOLA
