-name: Test telegram module
  hosts: localhost
  connection: local
  tasks:
    - name: Send test message
      telegram:
        token: "bot765291265:AAFC-buv3Pd_Mu2fwReeLlMhfaiRop5WN_4"
        chat_id: -258533565
        msg: "Message sent from Ansible playbook :)"
