---
- hosts: JbossTest 
  remote_user: root
  tasks:
    - name: Stop service jboss
      service:
       name: jboss-as-standalone
       state: stopped
    - name: Test telegram module
      hosts: localhost
      connection: local
    tasks:
      - name: Send test message
        telegram:
        token: "bot304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8"
        chat_id: 6343788
        msg: "Message sent from Ansible playbook :)"
