---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Bajando Pagina
      shell: /etc/ansible/JbossTest/pag_mantenimiento_down.sh 
    - name: Notificacion Telegram 
      shell: /etc/ansible/JbossTest/smsDOWN.sh
    - name: Notificacion SMS
      shell: /etc/ansible/JbossTest/notificacionLoteDown.sh
   
