---
- hosts: ApacheTest
  remote_user: root
  tasks:
    - name: Subiendo Pagina
      shell: /etc/ansible/JbossTest/pag_mantenimiento_up.sh 
    - name: Notificacion 
      shell: /etc/ansible/JbossTest/smsUP.sh
   
