---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Subiendo Pagina
      shell: /etc/ansible/JbossTest/pag_mantenimiento_up.sh
    - name: Notificacion Telegram
      shell: /etc/ansible/JbossTest/smsUP.sh
    - name: Notificacino SMS
      shell: /etc/ansible/JbossTest/notificacionLoteUp.sh
      
